source "%val{config}/bundle/kak-bundle/rc/kak-bundle.kak"
bundle-noload kak-bundle https://codeberg.org/jdugan6240/kak-bundle

bundle kak-lsp https://github.com/kak-lsp/kak-lsp %{
  # Configure here...
  # map global user l %{:enter-user-mode lsp<ret>} -docstring "LSP mode"
}

bundle-install-hook kak-lsp %{
  # Any shell code that needs to be run goes here...
  cargo install --locked --force --path .
}

bundle-cleaner kak-lsp %{
  rm ~/.cargo/bin/kak-lsp
}

colorscheme kaleidoscope-dark

set-option global tabstop 2

set-option global indentwidth 2  # indent with 2 spaces

# keep 1 line and 3 columns displayed around the cursor
set-option global scrolloff 1,3

# display line numbers
add-highlighter global/ number-lines -hlcursor

# highlight trailing spaces
add-highlighter global/ regex \h+$ 0:Error

# softwrap long lines
add-highlighter global/ wrap -word -indent

# clipboard management mappings
# map -docstring "yank the selection into the clipboard" global user y "<a-|> xsel -i<ret>"
# map -docstring "paste the clipboard" global user p "<a-!> xsel<ret>"


